#ifndef __ISIS_CONST__
#define __ISIS_CONST__

#define ISIS_ETH_PKT_TYPE      131
#define ISIS_PTP_HELLO_PKT_TYPE 17
#define ISIS_LSP_PKT_TYPE      18

#define ISIS_DEFAULT_HELLO_INTERVAL 3
#define ISIS_DEFAULT_INTF_COST 10
#define ISIS_HOLD_TIME_FACTOR 2


/* ISIS TLVs */
#define ISIS_TLV_HOSTNAME 137 //AS PER STANDARD
#define ISIS_TLV_RTR_ID   134 //AS PER STANDARD
#define ISIS_TLV_IF_IP    132 //AS PER STANDARD
#define ISIS_TLV_HOLD_TIME  5
#define ISIS_TLV_METRIC_VAL 6
#define ISIS_TLV_IF_INDEX   4 //AS PER STANDARD
#define ISIS_TLV_IF_MAC  131

#define ISIS_CONFIG_TRACE "ISIS(CONFIG)"

#endif